### ISSUE TITLE
when will the datasets be released?

### ISSUE THREAD

**Issue by BowieHsu** [switchablenorms/DeepFashion2#1]
Hi, thank you for your solid work.
I am wondering when will the datasets be released?

**Comment by cissoidx** [comment]
same question here.

**Comment by vivienzou1** [comment]
same question here.

**Comment by kulasama** [comment]
same question here.

**Comment by nationalflag** [comment]
and the trained models?

**Comment by PaulChongPeng** [comment]
Same question.
Wish the datasets and the trained models to be released soon.

**Comment by DouYishun** [comment]
Same question.

**Comment by Shenghsin** [comment]
Excellent work, when will the datasets be released?

**Comment by DaPenggg** [comment]
Same question.

**Comment by dimtsi** [comment]
Great work. I am also curious on whether the datasets will be released soon..

**Comment by willard-yuan** [comment]
Same question.

**Comment by lamhoangtung** [comment]
Same question here

**Comment by sorinpanduru** [comment]
Hello!
Can't even download the val dataset ? There's only the .txt files, but no images nor bbox annotations. 
When can we have these available ?

**Comment by StanislasBertrand** [comment]
Same question ! cant find the validation set seither

**Comment by AlexDut** [comment]
Very cool ! Looking forward to seeing the  datasets released.

**Comment by claeyzre** [comment]
Awesome, do you know when will the dataset be released ?

**Comment by bmetge** [comment]
Sounds great ! Can't wait for the release like all the folks above !!

**Comment by askmuhsin** [comment]
There is a similar dataset published by Tianchi (about 100k apparels annotated with 24 key-points). Maybe something to work on until this dataset is out. ;) 
https://tianchi.aliyun.com/competition/entrance/231670/information (sign up is required)

**Comment by shaayaansayed** [comment]
very cool, hoping for the release to happen soon!

**Comment by Erim32** [comment]
same question

**Comment by Holim0711** [comment]
same question!

**Comment by bwanglzu** [comment]
mark

**Comment by JustinhoCHN** [comment]
每日一问，数据集要发布了吗？感谢你们的工作~

**Comment by deep1blue** [comment]
Kudos. This is amazing work, love it! A question I have: When will the landmark and img data be released to rest of the mortal souls like us?

**Comment by geyuying** [comment]
Dear all,
We will organize challenges in 2019 ICCV workshop and DeepFashion2 dataset will be released at that time. Stay tuned for our upcoming workshop.
Thank you!

**Comment by bwanglzu** [comment]
![image](https://user-images.githubusercontent.com/9794489/56813727-dce80e00-683d-11e9-8fc1-8c54d5062865.png)

**Comment by geyuying** [comment]
Dear all,
2019 ICCV Worskshop website is available now in https://sites.google.com/view/cvcreative/home?authuser=0. Links to DeepFashion2 challenges will be released on June 1st. Stay tuned for our upcoming workshop and challenges.
Thank you!

**Comment by geyuying** [comment]
Dear all,
DeepFashion2 challenges begin now in https://sites.google.com/view/cvcreative/home?authuser=0. Looking forward to your participation!
Thank you!

**Comment by JustinhoCHN** [comment]
@geyuying thank you for your work! Are you planning enable the competition teams? Is it only allows personal submission?

**Comment by geyuying** [comment]
@JustinhoCHN Competition teams are available now.
