### ISSUE TITLE
API error

### ISSUE THREAD

**Issue by ahmedselim2017** [switchablenorms/DeepFashion2#19]
When I run 2 ` deepfashion2_test.py` file with python 2.7 it says `NameError: name 'annFile' is not defined`.

**Comment by geyuying** [comment]
Please download json_for_validation.zip in [https://drive.google.com/drive/u/2/folders/125F48fsMBz2EF0Cpqk6aaHet5VH399Ok](url) and define the path of 'annFile'. For example, annFile = '/data/keypoints_val_vis_and_occ.json'.

**Comment by ahmedselim2017** [comment]
Thanks, and now what should I define for `resFile`?

**Comment by geyuying** [comment]
Your result file. You can refer to [https://github.com/switchablenorms/DeepFashion2/blob/master/evaluation/evaluation.md](url) for details.

**Comment by ahmedselim2017** [comment]
Thanks a lot

**Comment by Yijia-Chen** [comment]
Are we supposed to create the result files before testing? I didn't quite understand what evaluation.md says about this.
