### ISSUE TITLE
How to visualize with result json file?

### ISSUE THREAD

**Issue by seokhyeonSong** [switchablenorms/DeepFashion2#20]
Hi. Thanks for sharing such a nice codes.

I'm a student who studies CV and I read it from paperswithcode.

I wanna visualize this code but I have no idea.

I understood that result json files are the information of bbox, segm etc... 

But I don't know how to visualize with it....

If you've already uploaded the code to visualize, then I'm sorry that I haven't read it in details

**Comment by geyuying** [comment]
@seokhyeonSong Do you want to visualize annotations of DeepFashion2 or visualize predicted results from network?

**Comment by seokhyeonSong** [comment]
@geyuying I found how to train and I'm training it.

what I want to know is how to visualize with predicted result from network.

If I make a pre-trained model, then what should I have to do with which py file?

sorry for just my ignorance...

**Comment by geyuying** [comment]
Our framework is based on Detectron, and we use Detectron/tools/infer_simple.py for visualization. You can refer to https://github.com/facebookresearch/Detectron/blob/master/GETTING_STARTED.md for details.

**Comment by seokhyeonSong** [comment]
@geyuying 

Thanks for your help 

I'll try it!

**Comment by seokhyeonSong** [comment]
@geyuying 

Sorry for asking again..

I've tried sample_infer.py as python infer_simple.py --cfg ../configs/12_2017_baselines/e2e_faster_rcnn_R-50-FPN_1x.yaml --output-dir ./ --image-ext jpg --wts ../../match_rcnn/logs/deepfashion220190808T0916/mask_rcnn_deepfashion2_0005.h5 ./

but Detectron it seems to be cannot load h5 weight file..

I've got new h5 file by running match_rcnn's main.py

Is h5 file have to be transformed?

**Comment by jia0511** [comment]
Hello, seokhyeonSong，


I am a deep learning development worker.I am glad to see that I am also working on this project. I am also interested in this project, but I am a beginner and don't know how to start it. Could you give me some help?I come from wuxi, China. My name is jack.




------------------ 原始邮件 ------------------
发件人: "seokhyeonSong"<notifications@github.com>;
发送时间: 2019年8月9日(星期五) 上午9:07
收件人: "switchablenorms/DeepFashion2"<DeepFashion2@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [switchablenorms/DeepFashion2] How to visualize with result jsonfile? (#20)




@geyuying
 
Sorry for asking again..
 
I've tried sample_infer.py as python infer_simple.py --cfg ../configs/12_2017_baselines/e2e_faster_rcnn_R-50-FPN_1x.yaml --output-dir ./ --image-ext jpg --wts ../../match_rcnn/logs/deepfashion220190808T0916/mask_rcnn_deepfashion2_0005.h5 ./
 
but Detectron it seems to be cannot load h5 weight file..
 
I've got new h5 file by running match_rcnn's main.py
 
Is h5 file have to be transformed?

**Comment by seokhyeonSong** [comment]
@jia0511 

run evaluation/deepfasion2_to_coco.py to get json file

you may run this code with validation dataset and train dataset

Then you may get 2 json files.

Then run match_rcnn's main.py 

You have to change settings with your environment

Then training will be started

That's what I've got known... 

It could be wrong

**Comment by jia0511** [comment]
Thank you for your help, 
but I tried to run evaluation/ deepfasion2_to_coke.py, 
but it always prompted an error, can you analyze your trained model? 
I just want to see the final verification effect. 




------------------ 原始邮件 ------------------
发件人: "seokhyeonSong"<notifications@github.com>;
发送时间: 2019年8月9日(星期五) 上午9:44
收件人: "switchablenorms/DeepFashion2"<DeepFashion2@noreply.github.com>;
抄送: "☆后街&男孩"<136324298@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [switchablenorms/DeepFashion2] How to visualize with result jsonfile? (#20)




@jia0511
 
run evaluation/deepfasion2_to_coco.py to get json file
 
you may run this code with validation dataset and train dataset
 
Then you may get 2 json files.
 
Then run match_rcnn's main.py
 
You have to change settings with your environment
 
Then training will be started
 
That's what I've got known...
 
It could be wrong

**Comment by jia0511** [comment]
Or you can tell me which file the evaluation/ deepfasion2_to_coke.py code variable json_name replaces with in the data set?Could you tell me how to operate it specifically?Thank you very much!
 




------------------ 原始邮件 ------------------
发件人: "seokhyeonSong"<notifications@github.com>;
发送时间: 2019年8月9日(星期五) 上午9:44
收件人: "switchablenorms/DeepFashion2"<DeepFashion2@noreply.github.com>;
抄送: "☆后街&男孩"<136324298@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [switchablenorms/DeepFashion2] How to visualize with result jsonfile? (#20)




@jia0511
 
run evaluation/deepfasion2_to_coco.py to get json file
 
you may run this code with validation dataset and train dataset
 
Then you may get 2 json files.
 
Then run match_rcnn's main.py
 
You have to change settings with your environment
 
Then training will be started
 
That's what I've got known...
 
It could be wrong

**Comment by seokhyeonSong** [comment]
@jia0511 

cuz This git's owner shares datasets to only the people who send google form

and trained model can be obtained by dataset so it will be impossible sry

**Comment by seokhyeonSong** [comment]
@jia0511 
you have to change 

json_name ~~, image_name ~~ (row 108,109) <- the link to dataset's annos folder and image folder

 json_name (row 234) <- the name of json file to create

**Comment by jia0511** [comment]
Thank you for your help. 

I successfully got deepfashion2.json file using the verification data set, but I ran python evaluation/ deepfasion2_to_coke.py error: name 'num_images' is not defined,(row 107)

Is this variable to be manually rewritten based on the amount of validation or training data?





------------------ 原始邮件 ------------------
发件人: "seokhyeonSong"<notifications@github.com>;
发送时间: 2019年8月9日(星期五) 上午10:06
收件人: "switchablenorms/DeepFashion2"<DeepFashion2@noreply.github.com>;
抄送: "☆后街&男孩"<136324298@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [switchablenorms/DeepFashion2] How to visualize with result jsonfile? (#20)




@jia0511
 you have to change
 
json_name ~~, image_name ~~ (row 108,109) <- the link to dataset's annos folder and image folder
 
json_name (row 234) <- the name of json file to create

**Comment by seokhyeonSong** [comment]
@jia0511  

You also change num_images to the number of images train & validation has

**Comment by jia0511** [comment]
I see. Thank you very much for your help.


------------------ 原始邮件 ------------------
发件人: "seokhyeonSong"<notifications@github.com>;
发送时间: 2019年8月9日(星期五) 上午10:40
收件人: "switchablenorms/DeepFashion2"<DeepFashion2@noreply.github.com>;
抄送: "☆后街&男孩"<136324298@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [switchablenorms/DeepFashion2] How to visualize with result jsonfile? (#20)




@jia0511
 
You also change num_images to the number of images train & validation has

**Comment by seokhyeonSong** [comment]
I found how to train with sample_infer.py

make json file with deepfashion dataset with mtcnn's main.py

and run with this code https://github.com/facebookresearch/Detectron/blob/master/GETTING_STARTED.md#training-a-model-with-detectron

but dataset have to be changed

change Detectron/detectron/datasets/dataset_catalog.py
-> add new available datasets with deepfashion train & test with image files and json files

change Detectron/configs/getting_started/config_which_you_want
-> change DATASETS with new available datasets' name which you made at  dataset_catalog.py

and then run train code with https://github.com/facebookresearch/Detectron/blob/master/GETTING_STARTED.md#training-a-model-with-detectron then train will be started

I've just started train but it would be make it visualize with the weights file that made with this code and config files that provided with detectron

Thanks for great help @geyuying
