### ISSUE TITLE
How to visualize? (final)

### ISSUE THREAD

**Issue by seokhyeonSong** [switchablenorms/DeepFashion2#23]
Sorry for frequent issue makings...

I had similar issue before at here https://github.com/switchablenorms/DeepFashion2/issues/20

and I thought that i have to train and visualize as Detectron

And finally i trained and visualized as Detectron, I got accurate bbox but categories are different which 

means skirt -> boat, shirt -> person like this

I realized that it was wrong with using detectron 

And I read intensively your git 

I think that 
1. make coco type json with tools/deepfashion2coco.py
2. train with main.py and and make color splashed image(I think it is optional and usage is segmentation right?)
3. visualize with lib/visualize.py but I cannot find how to use visualize.py

there's no and arguments or init or main ....

to visualize with detectron it need pkl type weight and yaml type configs

but match_rcnn makes h5 type weight and relative configs...

Would you please how to visualize with key & segmentation & bbox?
ex) which code can execute visualize.py or which can transform h5 and config into pkl and yaml type ...

**Comment by sharon-samson** [comment]
Did you got the visualized landmark output? Can you please share the code?
