### ISSUE TITLE
Some samples dont have landmarks ?

### ISSUE THREAD

**Issue by SCP-173-cool** [switchablenorms/DeepFashion2#24]
When I deal with the dataset, I found `000540` in trainset does not have landmark.
Could you please explain the question?
![image](https://user-images.githubusercontent.com/22118890/63929572-3f6b4800-ca84-11e9-8ea9-f7034fce0273.png)

**Comment by geyuying** [comment]
Yes, it happens when  a clothing item in an image has no visible or occluded defined landmark.  In deepfashion2, at least one clothing item in each image is annotated with landmarks.

**Comment by SCP-173-cool** [comment]
@geyuying Thanks!

**Comment by TDBTECHNO** [comment]
How did you use visualizing code?
