### ISSUE TITLE
Commercial Usage To Build Models

### ISSUE THREAD

**Issue by drreddy** [switchablenorms/DeepFashion2#3]
Hi,

In the Google Form received via email, it is mentioned the dataset is available only for non-commerical research purpose. Is there any commercial license available for the dataset, if we need to use the data to create some models for a commercial product.

**Comment by geyuying** [comment]
Commercial license is not available for DeepFashon2 dataset.

**Comment by kilho** [comment]
I am belong to a commercial company. Can I use this data if I use this data only for publishing a paper?
