### ISSUE TITLE
Different number of keypoins

### ISSUE THREAD

**Issue by amirassov** [switchablenorms/DeepFashion2#35]
Hi! Keypoint’s location is modeled as a one-hot mask. And it is done with `Conv` or `ConvTranspose` layer, where `output_channel_size = num_keypoints`. I see here: [1](https://github.com/facebookresearch/Detectron/blob/master/detectron/modeling/keypoint_rcnn_heads.py#L75
) [2](https://github.com/facebookresearch/Detectron/blob/master/detectron/modeling/keypoint_rcnn_heads.py#L88
)
But number of keypoints in DeepFashion2 is different for different classes (for example, in COCO dataset num_keypoints=17). How is this problem solved @geyuying ?

**Comment by amirassov** [comment]
I found solution from https://github.com/switchablenorms/DeepFashion2/blob/master/evaluation/deepfashion2_to_coco.py#L18.

**Comment by bhyzhao** [comment]
> Hi! Keypoint’s location is modeled as a one-hot mask. And it is done with `Conv` or `ConvTranspose` layer, where `output_channel_size = num_keypoints`. I see here: [1](https://github.com/facebookresearch/Detectron/blob/master/detectron/modeling/keypoint_rcnn_heads.py#L75) [2](https://github.com/facebookresearch/Detectron/blob/master/detectron/modeling/keypoint_rcnn_heads.py#L88)
> But number of keypoints in DeepFashion2 is different for different classes (for example, in COCO dataset num_keypoints=17). How is this problem solved @geyuying ?

hi, @amirassov  ,
Do you solve the problem and how?
It seems that the deepfashion2_to_coco.py concatenates all 294 keypoints together for each cloth. That is, the maximum number of valid keypoints is only 39(long sleeve outwear). How to handle this unbalance between negative and positive labels?

**Comment by mtroym** [comment]
@geyuying could you publish more details on how to handle the unbalance problem in match rcnn baseline model?
