### ISSUE TITLE
what is mean key+class

### ISSUE THREAD

**Issue by HansolEom** [switchablenorms/DeepFashion2#50]
![Screenshot from 2020-03-24 17-27-07](https://user-images.githubusercontent.com/45479160/77404264-cc953600-6df4-11ea-9325-6647b4478646.png)

In customer to shop, does key + class mean adding landmarks skeletons and classes?
I don't know what the key means.

**Comment by joppichristian** [comment]
Yes, I think it means adding landmarks skeletons and classes.

**Comment by HansolEom** [comment]
> Yes, I think it means adding landmarks skeletons and classes.

Thank you for your response.
