### ISSUE TITLE
Error while convert deepfashion2 to coco format dataset

### ISSUE THREAD

**Issue by VyBui** [switchablenorms/DeepFashion2#56]
Dear @geyuying, while converting DF2 to Coco according to this script: https://github.com/switchablenorms/DeepFashion2/blob/master/evaluation/deepfashion2_to_coco.py

There is an error that occurs due to Unresolved reference "num_images" line 107.

I want to ask if you also got this issue?

Thanks

**Comment by Alucard700** [comment]
Hi @VyBui have you resolved that issue "num_images" line 107.
If so , let me know how you resolved it.

Thanks
