### ISSUE TITLE
Which tool did you use to annotate the image?

### ISSUE THREAD

**Issue by asurada404** [switchablenorms/DeepFashion2#68]
Thanks for your kindness to share the dataset.
Could you please tell me which tool did you used to annotate the dataset?
I want to add some custom data in the same format.

**Comment by geyuying** [comment]
I am sorry that the software is not open source.

**Comment by asurada404** [comment]
Thanks for your reply.

**Comment by Loc-VD** [comment]
Can you share the name of the tool ?
