### ISSUE TITLE
Did'nt get password for datasets

### ISSUE THREAD

**Issue by ahmedselim2017** [switchablenorms/DeepFashion2#8]
I  filled the form 2 days ago but didn't get the password for datasets. Is there any problems with my answers for form or email?

**Comment by fzp8656342** [comment]
Me too, I filed the form since last week, but didn't get the password.

**Comment by MrPeker** [comment]
Same here...

**Comment by sguuaa** [comment]
Me too

**Comment by geyuying** [comment]
Sorry for the late reply.
Something went wrong with the form before and we have updated the form.
Please fill in the form again. If you can‘t, send email to yyge13@gmail.com and I will email you the password.

**Comment by harutk7** [comment]
hello i have filled the form and send email also. can you please send me also the password. thanks

**Comment by geyuying** [comment]
Please send e-mails to ***@***.***
