### ISSUE TITLE
Where is 'val_query.json' and 'val_gallery.json' ?

### ISSUE THREAD

**Issue by lenscloth** [switchablenorms/DeepFashion2#9]
"We provide keypoints_val_vis.json, keypoints_val_vis_and_occ.json, val_query.json and val_gallery.json for evaluation of validation set. You can get validation score locally using ..."

In the README.md, it is mentioned 'val_query.json' and 'val_gallery.json' files are provided.
But I cannot find those two files neither in github nor in downloaded dataset.
Can you tell me how can get those files?

**Comment by geyuying** [comment]
json_for_validation.zip has been uploaded to google drive.
